create table `users` (
  `id` INT AUTO_INCREMENT NOT NULL
  ,`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  ,`updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  ,`username` VARCHAR(30) NOT NULL
  ,`datetime` DATETIME DEFAULT CURRENT_TIMESTAMP
  ,`is_deleted` TINYINT(1) NOT NULL DEFAULT 0
  ,PRIMARY KEY (id)
)
;
